// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/plugin_service.proto

package plugin_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传插件请求
type UploadPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // 插件文件内容
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                          // 文件名
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPluginRequest) Reset() {
	*x = UploadPluginRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPluginRequest) ProtoMessage() {}

func (x *UploadPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPluginRequest.ProtoReflect.Descriptor instead.
func (*UploadPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadPluginRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *UploadPluginRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadPluginRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 上传插件响应
type UploadPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PluginId      string                 `protobuf:"bytes,3,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPluginResponse) Reset() {
	*x = UploadPluginResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPluginResponse) ProtoMessage() {}

func (x *UploadPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPluginResponse.ProtoReflect.Descriptor instead.
func (*UploadPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadPluginResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *UploadPluginResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// 列出插件请求
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListPluginsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 插件信息
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	License       string                 `protobuf:"bytes,6,opt,name=license,proto3" json:"license,omitempty"`
	Provider      string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	State         string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	Capabilities  []*CapabilityInfo      `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_proto_plugin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{3}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *PluginInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PluginInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PluginInfo) GetCapabilities() []*CapabilityInfo {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// 能力信息
type CapabilityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Models        []string               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityInfo) Reset() {
	*x = CapabilityInfo{}
	mi := &file_proto_plugin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityInfo) ProtoMessage() {}

func (x *CapabilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityInfo.ProtoReflect.Descriptor instead.
func (*CapabilityInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CapabilityInfo) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

// 列出插件响应
type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Plugins       []*PluginInfo          `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListPluginsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// 获取模型请求
type GetModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsRequest) Reset() {
	*x = GetModelsRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsRequest) ProtoMessage() {}

func (x *GetModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsRequest.ProtoReflect.Descriptor instead.
func (*GetModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelsRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *GetModelsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetModelsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取模型响应
type GetModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Models        map[string]*ModelList  `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: capability_type, value: model list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsResponse) Reset() {
	*x = GetModelsResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsResponse) ProtoMessage() {}

func (x *GetModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsResponse.ProtoReflect.Descriptor instead.
func (*GetModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetModelsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetModelsResponse) GetModels() map[string]*ModelList {
	if x != nil {
		return x.Models
	}
	return nil
}

type ModelList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelList) Reset() {
	*x = ModelList{}
	mi := &file_proto_plugin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelList) ProtoMessage() {}

func (x *ModelList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelList.ProtoReflect.Descriptor instead.
func (*ModelList) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{8}
}

func (x *ModelList) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

// 启用插件请求
type EnablePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePluginRequest) Reset() {
	*x = EnablePluginRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePluginRequest) ProtoMessage() {}

func (x *EnablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePluginRequest.ProtoReflect.Descriptor instead.
func (*EnablePluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{9}
}

func (x *EnablePluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *EnablePluginRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 启用插件响应
type EnablePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePluginResponse) Reset() {
	*x = EnablePluginResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePluginResponse) ProtoMessage() {}

func (x *EnablePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePluginResponse.ProtoReflect.Descriptor instead.
func (*EnablePluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{10}
}

func (x *EnablePluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnablePluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 禁用插件请求
type DisablePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePluginRequest) Reset() {
	*x = DisablePluginRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePluginRequest) ProtoMessage() {}

func (x *DisablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePluginRequest.ProtoReflect.Descriptor instead.
func (*DisablePluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{11}
}

func (x *DisablePluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *DisablePluginRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 禁用插件响应
type DisablePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePluginResponse) Reset() {
	*x = DisablePluginResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePluginResponse) ProtoMessage() {}

func (x *DisablePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePluginResponse.ProtoReflect.Descriptor instead.
func (*DisablePluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{12}
}

func (x *DisablePluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisablePluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 删除插件请求
type DeletePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePluginRequest) Reset() {
	*x = DeletePluginRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePluginRequest) ProtoMessage() {}

func (x *DeletePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePluginRequest.ProtoReflect.Descriptor instead.
func (*DeletePluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeletePluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *DeletePluginRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 删除插件响应
type DeletePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePluginResponse) Reset() {
	*x = DeletePluginResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePluginResponse) ProtoMessage() {}

func (x *DeletePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePluginResponse.ProtoReflect.Descriptor instead.
func (*DeletePluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 向量化请求
type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{15}
}

func (x *EmbedRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 向量化响应
type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Dimensions    int32                  `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{16}
}

func (x *EmbedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmbedResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *EmbedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 批量向量化请求
type EmbedBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Texts         []string               `protobuf:"bytes,2,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchRequest) Reset() {
	*x = EmbedBatchRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchRequest) ProtoMessage() {}

func (x *EmbedBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchRequest.ProtoReflect.Descriptor instead.
func (*EmbedBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{17}
}

func (x *EmbedBatchRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *EmbedBatchRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

// 批量向量化响应
type EmbedBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results       []*EmbeddingResult     `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchResponse) Reset() {
	*x = EmbedBatchResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchResponse) ProtoMessage() {}

func (x *EmbedBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchResponse.ProtoReflect.Descriptor instead.
func (*EmbedBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{18}
}

func (x *EmbedBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmbedBatchResponse) GetResults() []*EmbeddingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EmbedBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EmbeddingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResult) Reset() {
	*x = EmbeddingResult{}
	mi := &file_proto_plugin_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResult) ProtoMessage() {}

func (x *EmbeddingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResult.ProtoReflect.Descriptor instead.
func (*EmbeddingResult) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{19}
}

func (x *EmbeddingResult) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// 重排序请求
type RerankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Documents     []*RerankDocument      `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankRequest) Reset() {
	*x = RerankRequest{}
	mi := &file_proto_plugin_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankRequest) ProtoMessage() {}

func (x *RerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankRequest.ProtoReflect.Descriptor instead.
func (*RerankRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{20}
}

func (x *RerankRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RerankRequest) GetDocuments() []*RerankDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

// 重排序文档
type RerankDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankDocument) Reset() {
	*x = RerankDocument{}
	mi := &file_proto_plugin_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankDocument) ProtoMessage() {}

func (x *RerankDocument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankDocument.ProtoReflect.Descriptor instead.
func (*RerankDocument) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{21}
}

func (x *RerankDocument) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RerankDocument) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RerankDocument) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 重排序响应
type RerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results       []*RerankResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResponse) Reset() {
	*x = RerankResponse{}
	mi := &file_proto_plugin_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResponse) ProtoMessage() {}

func (x *RerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResponse.ProtoReflect.Descriptor instead.
func (*RerankResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{22}
}

func (x *RerankResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RerankResponse) GetResults() []*RerankResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RerankResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 重排序结果
type RerankResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *RerankDocument        `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResult) Reset() {
	*x = RerankResult{}
	mi := &file_proto_plugin_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResult) ProtoMessage() {}

func (x *RerankResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResult.ProtoReflect.Descriptor instead.
func (*RerankResult) Descriptor() ([]byte, []int) {
	return file_proto_plugin_service_proto_rawDescGZIP(), []int{23}
}

func (x *RerankResult) GetDocument() *RerankDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *RerankResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RerankResult) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_proto_plugin_service_proto protoreflect.FileDescriptor

const file_proto_plugin_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/plugin_service.proto\x12\x0eplugin_service\"m\n" +
	"\x13UploadPluginRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"\x83\x01\n" +
	"\x14UploadPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tplugin_id\x18\x03 \x01(\tR\bpluginId\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\"-\n" +
	"\x12ListPluginsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\x94\x02\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x18\n" +
	"\alicense\x18\x06 \x01(\tR\alicense\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12B\n" +
	"\fcapabilities\x18\t \x03(\v2\x1e.plugin_service.CapabilityInfoR\fcapabilities\"<\n" +
	"\x0eCapabilityInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\"e\n" +
	"\x13ListPluginsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\aplugins\x18\x02 \x03(\v2\x1a.plugin_service.PluginInfoR\aplugins\"a\n" +
	"\x10GetModelsRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"\xca\x01\n" +
	"\x11GetModelsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12E\n" +
	"\x06models\x18\x02 \x03(\v2-.plugin_service.GetModelsResponse.ModelsEntryR\x06models\x1aT\n" +
	"\vModelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.plugin_service.ModelListR\x05value:\x028\x01\"#\n" +
	"\tModelList\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\"K\n" +
	"\x13EnablePluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"J\n" +
	"\x14EnablePluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x14DisablePluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"K\n" +
	"\x15DisablePluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x13DeletePluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"J\n" +
	"\x14DeletePluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\fEmbedRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"}\n" +
	"\rEmbedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x05R\n" +
	"dimensions\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"F\n" +
	"\x11EmbedBatchRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x14\n" +
	"\x05texts\x18\x02 \x03(\tR\x05texts\"\x7f\n" +
	"\x12EmbedBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\aresults\x18\x02 \x03(\v2\x1f.plugin_service.EmbeddingResultR\aresults\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"/\n" +
	"\x0fEmbeddingResult\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\"\x80\x01\n" +
	"\rRerankRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12<\n" +
	"\tdocuments\x18\x03 \x03(\v2\x1e.plugin_service.RerankDocumentR\tdocuments\"P\n" +
	"\x0eRerankDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"x\n" +
	"\x0eRerankResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\aresults\x18\x02 \x03(\v2\x1c.plugin_service.RerankResultR\aresults\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"t\n" +
	"\fRerankResult\x12:\n" +
	"\bdocument\x18\x01 \x01(\v2\x1e.plugin_service.RerankDocumentR\bdocument\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank2\x8c\x06\n" +
	"\rPluginService\x12Y\n" +
	"\fUploadPlugin\x12#.plugin_service.UploadPluginRequest\x1a$.plugin_service.UploadPluginResponse\x12V\n" +
	"\vListPlugins\x12\".plugin_service.ListPluginsRequest\x1a#.plugin_service.ListPluginsResponse\x12P\n" +
	"\tGetModels\x12 .plugin_service.GetModelsRequest\x1a!.plugin_service.GetModelsResponse\x12Y\n" +
	"\fEnablePlugin\x12#.plugin_service.EnablePluginRequest\x1a$.plugin_service.EnablePluginResponse\x12\\\n" +
	"\rDisablePlugin\x12$.plugin_service.DisablePluginRequest\x1a%.plugin_service.DisablePluginResponse\x12Y\n" +
	"\fDeletePlugin\x12#.plugin_service.DeletePluginRequest\x1a$.plugin_service.DeletePluginResponse\x12D\n" +
	"\x05Embed\x12\x1c.plugin_service.EmbedRequest\x1a\x1d.plugin_service.EmbedResponse\x12S\n" +
	"\n" +
	"EmbedBatch\x12!.plugin_service.EmbedBatchRequest\x1a\".plugin_service.EmbedBatchResponse\x12G\n" +
	"\x06Rerank\x12\x1d.plugin_service.RerankRequest\x1a\x1e.plugin_service.RerankResponseB\x18Z\x16./proto/plugin_serviceb\x06proto3"

var (
	file_proto_plugin_service_proto_rawDescOnce sync.Once
	file_proto_plugin_service_proto_rawDescData []byte
)

func file_proto_plugin_service_proto_rawDescGZIP() []byte {
	file_proto_plugin_service_proto_rawDescOnce.Do(func() {
		file_proto_plugin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_service_proto_rawDesc), len(file_proto_plugin_service_proto_rawDesc)))
	})
	return file_proto_plugin_service_proto_rawDescData
}

var file_proto_plugin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_plugin_service_proto_goTypes = []any{
	(*UploadPluginRequest)(nil),   // 0: plugin_service.UploadPluginRequest
	(*UploadPluginResponse)(nil),  // 1: plugin_service.UploadPluginResponse
	(*ListPluginsRequest)(nil),    // 2: plugin_service.ListPluginsRequest
	(*PluginInfo)(nil),            // 3: plugin_service.PluginInfo
	(*CapabilityInfo)(nil),        // 4: plugin_service.CapabilityInfo
	(*ListPluginsResponse)(nil),   // 5: plugin_service.ListPluginsResponse
	(*GetModelsRequest)(nil),      // 6: plugin_service.GetModelsRequest
	(*GetModelsResponse)(nil),     // 7: plugin_service.GetModelsResponse
	(*ModelList)(nil),             // 8: plugin_service.ModelList
	(*EnablePluginRequest)(nil),   // 9: plugin_service.EnablePluginRequest
	(*EnablePluginResponse)(nil),  // 10: plugin_service.EnablePluginResponse
	(*DisablePluginRequest)(nil),  // 11: plugin_service.DisablePluginRequest
	(*DisablePluginResponse)(nil), // 12: plugin_service.DisablePluginResponse
	(*DeletePluginRequest)(nil),   // 13: plugin_service.DeletePluginRequest
	(*DeletePluginResponse)(nil),  // 14: plugin_service.DeletePluginResponse
	(*EmbedRequest)(nil),          // 15: plugin_service.EmbedRequest
	(*EmbedResponse)(nil),         // 16: plugin_service.EmbedResponse
	(*EmbedBatchRequest)(nil),     // 17: plugin_service.EmbedBatchRequest
	(*EmbedBatchResponse)(nil),    // 18: plugin_service.EmbedBatchResponse
	(*EmbeddingResult)(nil),       // 19: plugin_service.EmbeddingResult
	(*RerankRequest)(nil),         // 20: plugin_service.RerankRequest
	(*RerankDocument)(nil),        // 21: plugin_service.RerankDocument
	(*RerankResponse)(nil),        // 22: plugin_service.RerankResponse
	(*RerankResult)(nil),          // 23: plugin_service.RerankResult
	nil,                           // 24: plugin_service.GetModelsResponse.ModelsEntry
}
var file_proto_plugin_service_proto_depIdxs = []int32{
	4,  // 0: plugin_service.PluginInfo.capabilities:type_name -> plugin_service.CapabilityInfo
	3,  // 1: plugin_service.ListPluginsResponse.plugins:type_name -> plugin_service.PluginInfo
	24, // 2: plugin_service.GetModelsResponse.models:type_name -> plugin_service.GetModelsResponse.ModelsEntry
	19, // 3: plugin_service.EmbedBatchResponse.results:type_name -> plugin_service.EmbeddingResult
	21, // 4: plugin_service.RerankRequest.documents:type_name -> plugin_service.RerankDocument
	23, // 5: plugin_service.RerankResponse.results:type_name -> plugin_service.RerankResult
	21, // 6: plugin_service.RerankResult.document:type_name -> plugin_service.RerankDocument
	8,  // 7: plugin_service.GetModelsResponse.ModelsEntry.value:type_name -> plugin_service.ModelList
	0,  // 8: plugin_service.PluginService.UploadPlugin:input_type -> plugin_service.UploadPluginRequest
	2,  // 9: plugin_service.PluginService.ListPlugins:input_type -> plugin_service.ListPluginsRequest
	6,  // 10: plugin_service.PluginService.GetModels:input_type -> plugin_service.GetModelsRequest
	9,  // 11: plugin_service.PluginService.EnablePlugin:input_type -> plugin_service.EnablePluginRequest
	11, // 12: plugin_service.PluginService.DisablePlugin:input_type -> plugin_service.DisablePluginRequest
	13, // 13: plugin_service.PluginService.DeletePlugin:input_type -> plugin_service.DeletePluginRequest
	15, // 14: plugin_service.PluginService.Embed:input_type -> plugin_service.EmbedRequest
	17, // 15: plugin_service.PluginService.EmbedBatch:input_type -> plugin_service.EmbedBatchRequest
	20, // 16: plugin_service.PluginService.Rerank:input_type -> plugin_service.RerankRequest
	1,  // 17: plugin_service.PluginService.UploadPlugin:output_type -> plugin_service.UploadPluginResponse
	5,  // 18: plugin_service.PluginService.ListPlugins:output_type -> plugin_service.ListPluginsResponse
	7,  // 19: plugin_service.PluginService.GetModels:output_type -> plugin_service.GetModelsResponse
	10, // 20: plugin_service.PluginService.EnablePlugin:output_type -> plugin_service.EnablePluginResponse
	12, // 21: plugin_service.PluginService.DisablePlugin:output_type -> plugin_service.DisablePluginResponse
	14, // 22: plugin_service.PluginService.DeletePlugin:output_type -> plugin_service.DeletePluginResponse
	16, // 23: plugin_service.PluginService.Embed:output_type -> plugin_service.EmbedResponse
	18, // 24: plugin_service.PluginService.EmbedBatch:output_type -> plugin_service.EmbedBatchResponse
	22, // 25: plugin_service.PluginService.Rerank:output_type -> plugin_service.RerankResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_plugin_service_proto_init() }
func file_proto_plugin_service_proto_init() {
	if File_proto_plugin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_service_proto_rawDesc), len(file_proto_plugin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_service_proto_goTypes,
		DependencyIndexes: file_proto_plugin_service_proto_depIdxs,
		MessageInfos:      file_proto_plugin_service_proto_msgTypes,
	}.Build()
	File_proto_plugin_service_proto = out.File
	file_proto_plugin_service_proto_goTypes = nil
	file_proto_plugin_service_proto_depIdxs = nil
}
